export function GetTelephoneTable() {
  return [["楠梓廠分機明細", null, null, null, null, null, null, null, null, null, null, null, null, null], 
    ["跨廠加代號", "董事長/總經理室", null, "製布廠", null, "品保部", null, "業務處", null, "管理部", null, null, null, null], 
    [null, "陳建志", 200, "曾建源", 131, "吳美玲", "66007&141", "姓名", "分機", "姓名", "分機", null, null, null], 
    [88, "邱麗娟", 201, "曾聖揚", 132, "陳善財", 142, "廖彥嵐", 230, "林弘祥", 240, null, null, null], 
    [null, "王子維", 281, null, null, null, null, null, null, null, null, null, null, null], 
    [null, "呂季席", 282, null, 133, "戴曉昀", 143, "王俊諺", 231, "龔麗尹", 241, null, null, null], 
    [null, "謝沛卿", 206, "林虹妤", 134, "何明真", 144, "蘇莉螢", 232, "張斯涵", 242, null, null, null], 
    [null, "廠務課/環安", null, "何幸螢", 135, "巡檢人員", 506, "賴純姿", 234, "謝瑩瑩", 243, null, null, null], 
    [null, "邱燕秋", "66009&112", "陳麗如", 136, "採購/進出口", null, "林玉珠", 236, "財務處", null, null, null, null], 
    [null, "張婷婷", 113, null, 121, "林玉淑", 260, "許裕盛", 237, "黃敬甯", 210, null, null, null], 
    [null, "翁頂凱", 115, "現     場", 506, "蘇珮榕", 261, "李佩臻", 238, "蔡佩芬", 212, null, null, null], 
    [null, "林郁軒", 114, "夾層休息室", 158, "林士傑", 262, "吳信億", 251, "謝璇璇", 213, null, null, null], 
    [null, "會議室", null, null, null, "蔡旻芳", 263, "林晉加", 252, "王桂慧", 214, null, null, null], 
    [null, "1樓大會議室", 711, "資訊部", null, "陳宥衣", 267, "孟繁華", 254, "李靚娪", 215, null, null, null], 
    [null, "1樓小會議室", 712, "王天勤", 220, "陳靜青", 268, "蔡幸君", 255, "黃露嬉", 216, null, null, null], 
    [null, "2樓N21大會議室", 721, "張雅智", 221, "郭泂岑", 269, "盛思涵", 256, "吳宗瀚", 217, null, null, null], 
    [null, "2樓N22會議室", 722, "吳柄衡", 222, "工務部", null, "林彥亨", 257, "許淑芬", 218, null, null, null], 
    [null, "2樓N23會議室", 723, "謝嘉恩", 223, null, null, "施秀蕾", 258, null, null, null, null, null], 
    [null, "2樓N24會議室", 724, "馬恩奇", 224, "洪弘承", 122, null, null, null, null, null, null, null], 
    [null, null, null, "林旻毅", 225, "郭俊廷", 123, null, null, null, null, null, null, null], 
    [null, "守衛室", 119, "張耀壬", 226, "張文龍", 124, null, null, null, null, null, null, null], 
    [null, "總機", "07-3553688", "王仲益", 227, null, 125, null, null, null, null, null, null, null], 
    [null, "傳真", "07-3582091", null, null, null, 126, null, null, null, null, null, null, null], 
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null], 
    ["永安廠分機明細", null, null, null, null, null, null, null, null, null, null, null, null, null], 
    ["跨廠加代號", "總經理辦公室", null,"品保部", null, "製膜廠", null, "製布廠", null, null, null, null, null, null],
    [null, "總經理", 311, "吳美玲", 271, "黃招文", 121, "SP2主機", 511, null, null, null, null, null], 
    [77, "研發部", null, "林廷諭", 272, "徐維筠", 111, "折片", 514, null, null, null, null, null],
    [null, "廖炳森", 341, "空", 273, "黃士維", 122, null, null, null, null, null, null, null], 
    [null, "蔡亞彤", 343, "陳信偉", 274, "林蕙楹", 123, "環安總務", null, null, null, null, null, null], 
    [null, "邱副董", 351, "蕭欣霓", 275, "吳雪娥", 132, "陳饒仁", 112, null, null, null, null, null],
    [null, "王秋迪", 352, "空", 276, "蘇凱珊", 133, "卓佳縉", 113, null, null, null, null, null], 
    [null, "陳幼姍", 353, "巡檢", 277, "PE1-2", 501, "黃麒銘", 114, null, null, null, null, null], 
    [null, "蔡宜霖", 342, "一樓實驗室", 278, "PE3", 504, null, null, null, null, null, null, null],
    [null, "總經理室/資訊", null, "資材(倉儲)", null, "PE4", 505, "其他", null, null, null, null, null, null],
    [null, "邱泰政", 141, "李桂貞", 124, "PE6", 510, "三樓大會議室", 321, null, null, null, null, null],
    [null, "張智傑", 131, null, null, "CP4舊/CP1-3", "508/502", "地下室會客室B04", 101, null, null, null, null, null],
    [null, "康雅慈", 142, "工務部", null, "CP456", 509, "地下室會客室B01", 102, null, null, null, null, null], 
    [null, "王仲益", 143, "李福倫", "66008&161", "印刷", 506, "餐廳", 621, null, null, null, null, null], 
    [null, null, null, "郭峰瑲\n陳譽升", 162, "PEL-1貼合1", 503, "4號小倉 ", 522, null, null, null, null, null],
    [null, null, null, "陳貞玲", 163, "PEL-2貼合2", 507, "6號大倉", 622, null, null, null, null, null],
    [null, null, null, null, 166, null, null, null, null, null, null, null, null, null],
    [null, null, null, "孫宏竣", 167, null, null, null, null, null, null, null, null, null],
    [null, null, null, "鄭吉亨", 168, null, null, null, null, null, null, null, null, null],
    [null, "守衛室", 119, "空", "164/169", null, null, null, null, null, null, null, null, null], 
    [null, "總機", "07-6218600", "張進安/馬錦民", 170, null, null, null, null, null, null, null, null, null], 
    [null, "傳真", "07-6229200", null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    ["樹谷廠分機明細", null, null, null, null, null, null, null, null, null, null, null, null, null], 
    ["跨廠加代號", "製造處", null, "品保部", null, "消費品業務部", null, "管理部", null, null, null, null, null, null], 
    [null, "姓名", "分機", "姓名", "分機", "姓名", "分機", "姓名", "分機", null, null, null, null, null], 
    [66, "陳信宇", 131, "吳美玲", 240, null, "001", "林弘祥", null, null, null, null, null, null], 
    [null, "吳景逸", 132, "陳妍如", 241, "卓孫君", 250, "龔麗尹 / 謝瑩瑩", 161, null, null, null, null, null], 
    [null, "王彩淳", 133, "預留", 242, "楊佳盈", 210, "吳建龍", 164, null, null, null, null, null],
    [null, "陳又銓\n李憶姍", 134, "湯于慬", 243, "王建翔", 211, "郭威儀", 165,null, null, null, null, null], 
    [null, "徐偉智", 142, "黃麗瑩", 244, "楊雪珍", 214, null, null, null, null, null, null, null],
    [null, "梁思麗", 143, "陸盈均", 245, "李佩珍", 215, null, null, null, null, null, null, null],
    [null, "黃沛瑄", 144, "巡檢室", 151, "黃美亭", 225, null, null, null, null, null, null, null],
    [null, "曾文忠", 121, "實驗室/微生物 (2F)", 201, "研發部", null, "資材部", null, null, null, null, null, null],
    [null, "翁宜鴻", 122,"實驗室/理化 (2F)", 202, "廖炳森", 230, "林玉淑", 111, null, null, null, null, null],
    [null, "李砥中", 123, "工程部", null, "陳登文", 231, null, 162, null, null, null, null, null],
    [null, "蔡亞諠", 124, "黃健富", 136, "謝玉霞", 232, "邱燕秋 / 莊君珮", 113, null, null, null, null, null], 
    [null, null, 125, "陳志強", 135, "吳冠霖", 233, null, null, null, null, null, null, null],
    [null, "濕巾主機 (3F)", 305, "工務", 146, "林甫駿", 220, null, null, null, null, null, null, null], 
    [null, "濕巾調配 (3F)", 303, "楊偉仁", 145, "鄭廷緯", 221, null, null, null, null, null, null, null],
    [null, "濕巾包裝 (3F)", 304, null, null, "陳怡蓉", 222, null, null, null, null, null, null, null],
    [null, null, null, null, null, "謝瑜庭", 223, null, null, null, null, null, null, null], 
    [null, "守衛室", 119, null, null, null, null, null, null, null, null, null, null, null],
    [null, "總機", "06-5999888", null, null, null, null, null, null, null, null, null, null, null], 
    [null, "傳真", "06-5990066", null, null, null, null, null, null, null, null, null, null, null], 
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    ["越南廠分機明細", null, null, null, null, null, null, null, null, null, null, null, null, null],
    ["跨廠加代號", "姓名", "分機", "姓名", "分機", "姓名", "分機", "姓名", "分機", null, null, null, null, null], 
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [55, "主席 Chủ tịch", 101, "總會計師\nKế Toán Trưởng\n林青勇", 106, "特助 Trợ Lý TGĐ\nMs Soan\n裴氏金椿", 112, "QC- Ms Nga\n武氏清娥", 190, null, null, null, null, null],
    [null, "總經理室\nPhòng TGĐ (Albert)", 102, "採購 Thu Mua\n阮氏艷翠", 107, "人資 Nhân Sự\n范玉孝", null, "保衛室 Bảo Vệ", 191, null, null, null, null, null],
    [null, "會計 Kế Toán\n阮氏苞/潘氏翠", 103, "關務 Hải Quan\n陳氏嬌絨", 108, null, null, "廠長\nXưởng Trưởng\nMr Wang\n王春源", 194, null, null, null, null, null],
    [null, "HSE + Tổng Vụ HSE+ 總務\nMr Tòng\n范文財/梅清松", 104, "業務 Kinh Doanh\n陳青海/阮氏金芳", 109, null, null, "Quản Lý - QC\n高志文/陳典義/\n高氏美好", 195, null, null, null, null, null], 
    [null, "資訊管理 IT\n杜進日", 105, null, null, null, null, "耗材 Vật Tư - Sinh Quản\n裴春北/蘇金紅", 196, null, null, null, null, null], 
    [null, null, null, null, null, null, null, "更新：20240215", null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null]];
}